### ISSUE TITLE
在typecho 1.2.0，主题“G”条件下，该插件工作不正常。

### ISSUE THREAD

**Issue by randaiistephens** [AlanDecode/Typecho-Plugin-ExSearch#10]
已经按照插件说明完成安装，启用，保存，重建。
但是。。。如图，插件搜索框可以显示，但是什么都搜不到。

<img width="937" alt="图片" src="https://user-images.githubusercontent.com/108912506/207272518-583492fb-bb21-4407-a270-5d9273343212.png">

**Comment by buyufan** [comment]
我确定文件权限是正常的。
重建索引会打开一个新的空白页面，没有成功或失败的提示
